services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Comolo\SuperLoginClient\ContaoEdition\:
        resource: '../*'
        exclude: 
            - '../Resources/{config,services}'
            - '../Resources/contao/**'
            - '../Resources/config/**'

    Comolo\SuperLoginClient\ContaoEdition\Server\ServerManager:
        public: true
        arguments:
            $contaoFramework: '@contao.framework'

    Comolo\SuperLoginClient\ContaoEdition\User\RemoteUserManager:
        public: true

    Comolo\SuperLoginClient\ContaoEdition\Security\ContaoBackendLogin:
        public: true
        arguments:
            $contaoUserProvider: '@contao.security.backend_user_provider'
            $tokenStorage: '@security.token_storage'
            $authenticationUtils: '@security.authentication_utils'
            $contaoFramework: '@contao.framework'
            $session: '@contao.session.contao_backend'
            $eventDispatcher: '@event_dispatcher'
            $requestStack: '@request_stack'

    Comolo\SuperLoginClient\ContaoEdition\User\RemoteContaoOAuth2User:
        public: true

    Comolo\SuperLoginClient\ContaoEdition\Controller\AuthorizationController:
        public: true
        tags:
            - { name: controller.service_arguments }
            - { name: container.service_subscriber }
            - { name: kernel.event_subscriber }