services:
    Comolo\SuperLoginClient\ContaoEdition\Server\ServerManager:
        public: true
        autowire: true
        arguments:
            $contaoFramework: '@contao.framework'

    Comolo\SuperLoginClient\ContaoEdition\User\RemoteUserManager:
        public: true
        autowire: true

    Comolo\SuperLoginClient\ContaoEdition\Security\ContaoBackendLogin:
        public: true
        autowire: true
        arguments:
            $contaoUserProvider: '@contao.security.backend_user_provider'
            $tokenStorage: '@security.token_storage'
            $authenticationUtils: '@security.authentication_utils'
            $contaoFramework: '@contao.framework'
            $session: '@contao.session.contao_backend'
            $eventDispatcher: '@event_dispatcher'
            $requestStack: '@request_stack'

    Comolo\SuperLoginClient\ContaoEdition\User\RemoteContaoOAuth2User:
        public: true
        autowire: true

    Comolo\SuperLoginClient\ContaoEdition\Controller\AuthorizationController:
        public: true
        autowire: true
        arguments:
            $container: '@service_container'
        tags: ['controller.service_arguments']