services:
    Comolo\SuperLoginClient\ContaoEdition\Server\ServerManager:
        public: true
        autowire: true

    Comolo\SuperLoginClient\ContaoEdition\User\RemoteUserManager:
        public: true
        autowire: true

    Comolo\SuperLoginClient\ContaoEdition\Security\ContaoBackendLogin:
        public: true
        autowire: true
        arguments:
            $contaoUserProvider: '@contao.security.backend_user_provider'
            $tokenStorage: '@security.token_storage'
            $authenticationUtils: '@security.authentication_utils'

    Comolo\SuperLoginClient\ContaoEdition\User\RemoteContaoOAuth2User:
        public: true
        autowire: true

    Comolo\SuperLoginClient\ContaoEdition\Controller\AuthorizationController:
        public: true
        autowire: true
        tags: ['controller.service_arguments']